#!/usr/bin/env bash
# startup.sh - Quick startup guide for ParkMatrix AI MVP

echo "🚗 ParkMatrix AI - Smart Urban Parking Intelligence MVP"
echo "============================================================"
echo ""
echo "📦 Step 1: Install dependencies"
echo "   Command: pip install -r requirements.txt"
echo ""
echo "▶️  Step 2: Run the application"
echo "   Command: streamlit run app.py"
echo ""
echo "🌐 Step 3: Open in browser"
echo "   URL: http://localhost:8501"
echo ""
echo "============================================================"
echo ""
echo "📱 Features Available:"
echo ""
echo "  1. 🏠 Home - Problem/solution overview"
echo "  2. 📍 List Parking - Owner listing form"
echo "  3. 🔍 Find Parking - User search & discovery"
echo "  4. 🤖 AI Intelligence - Real CNN-LSTM predictions"
echo "  5. 📅 Booking & Payment - Transaction flow"
echo "  6. 📲 QR Code & Access - Booking verification"
echo "  7. 🏗️ Architecture - System design & roadmap"
echo ""
echo "============================================================"
echo ""
echo "💡 Tips for Demo:"
echo "  • Try the AI Intelligence tab - it's the showcase!"
echo "  • Use realistic data (location: Hitech City, price: ₹50/hr)"
echo "  • Complete a full booking flow to test QR generation"
echo "  • Check Architecture tab for scalability questions"
echo ""
echo "📚 Documentation:"
echo "  • README.md - Full project guide"
echo "  • MVP_QUICKSTART.md - Get started in 2 minutes"
echo "  • FEATURE_CHECKLIST.md - Detailed feature overview"
echo ""
echo "✅ Ready to impress your reviewers!"
echo ""

